project:
  type: website

website:
  title: "blog"
  navbar:
    background: primary
    search: true
    left:
      - text: "Profile"
        file: about.qmd
      - text: "Data Mining"
        file: data_mining.qmd
      - text: "Data_Visualization"
        file: data_vis.qmd
      - text: "Geocomputation"
        file: geo.qmd

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Profile"
        contents: 
          - about.qmd
      - section: "College"
        contents:
          - data_mining.qmd
          - data_vis.qmd
          - geo.qmd
    right:
      - icon: github
        href: https://github.com/ljw02220
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cerulean
    css: styles.css

