project:
  type: website

website:
  title: "Blog"
  navbar:
    background: primary
    search: true
    left:
      - text: "Profile"
        file: about.qmd
    right:
      - text: "about"
        file: new index.qmd
      - icon: github
        href: https://github.com/ljw02220
      - icon: twitter
        href: https://twitter.com
  sidebar:
    style: "docked"
    search: true
    contents: 
      - section: "Profile"
        contents: 
          - about.qmd
      - section: "College"
        contents:
          - data_mining.qmd
          - data_vis.qmd
          - geo.qmd
      - section: "Project"
        contents: 
          - machine learning.qmd
format:
  html:
    theme: cerulean
    css: styles.css

